DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(259) NOT NULL,
	email VARCHAR(311) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL
	
);